apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: grafana
    server: {{ .Values.spec.destination.server }}
  project: default
  source:
    path: charts/grafana
    repoURL: https://github.com/grafana/helm-charts
    targetRevision: HEAD
    helm:
      valuesObject:
        ingress:
          enabled: true
          annotations:
            cert-manager.io/cluster-issuer: letsencrypt-prod
            traefik.ingress.kubernetes.io/router.middlewares: default-redirect-https@kubernetescrd
          hosts:
            - grafana.marks.dev
          tls:
            - secretName: grafana-server-tls
              hosts:
                - grafana.marks.dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
