{{ if .Values.hlc-site.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hlc-site
  namespace: hlc-site
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: hlc-site
    server: {{ .Values.spec.destination.server }}
  project: default
  source:
    path: hlc-site
    repoURL: https://github.com/eaglerock1337/happy-little-cloud
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
{{ end }}