apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: prometheus
    server: {{ .Values.spec.destination.server }}
  project: default
  source:
    path: charts/prometheus
    repoURL: https://github.com/prometheus-community/helm-charts/
    targetRevision: HEAD
    helm:
      valuesObject:
        server:
          ingress:
            enabled: true
            hosts:
              - prometheus.marks.dev
            tls:
              - secretName: prometheus-server-tls
                hosts:
                  - prometheus.marks.dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
