apiVersion: v2
name: hlc-site
description: The Happy Little Cloud single-serving website.

type: application
version: 1.0.0
appVersion: "1.16.0"
maintainers:
  - name: Peter Marks
    url: https://marks.dev/