apiVersion: v1
kind: ConfigMap
metadata:
  name: cm-hlc-html
data:
{{ tpl (.Files.Glob "site/**.html").AsConfig . | indent 2 }}
---
apiVersion: v1
kind: Secret
type: Generic
metadata:
  name: bob-ross-gif
data:
  bob-ross.gif: {{ .Files.Get "site/bob-ross.gif" | b64enc }}
---
apiVersion: v1
kind: Secret
type: Generic
metadata:
  name: hlc-mp3
data:
  hlc.mp3: {{ .Files.Get "site/hlc.mp3" | b64enc }}
